spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQCFBu919Slk7RzZYzRu+Om8ZHatF9oOSoHUDH8xtdrUe5rVaaAmbzRQbfFwgLFmLUaRxFyv3wYz7RuzLYudN/zxA/E19XjhXL+Wg1sawhytmvkPh4/BgzXJzg/1u5ggvjSxDUfb0qxw8n8Z0QPyeGzhn+NHMTttalXKyEGNsO6I7yvFwdob2dnvGRF/3ub6GKgzkzjo95MB59f6CUeyB+G54lqcww/kfRjoonqvJFPnA4HA+4sllY84RvW8WQaTBfQB2Fh3TH4AywK3k6YT8tPF27w7XIesr5jXbrokvSc9/jl+OPOOXZadzVmHgLk7kZ4dDTcM9AEN0iwUCGVBmnBV4AlbJGC9PF2UuwbDAP/doCSblp7VdDK6xvQ3cL8Cf1Y='


token:
  expiration_time: 864000000
  secret: '{cipher}AQCGiTbYaKfH9O1NTsMDi1dub5tswd1toVJMwfcHGY5xCJFtT1G5qkcBFCcztgtNrnDgb8qVZ8Spueo9127dg6kpJFKGSb/RN2/IlkA0nMv9NgwwA9hUX4rJ4FhSWzzeP9gdqIw4N6QJgTfqGR/lImdzFZdfuvP9FgGd1ZyejkMWiDhvJroFK8VSzz9iJBAHWPTfYxSbLz/EB0enPqtgnPkVClL1UE5KHBKdDgApnWvTQroaOpq1hjXxhsq7ZPR/b4637HNqb5gpr/G8mbxUroeSHiHAUujMh/mpPPBq1fOpuCdq49kZ9UvYBLtDx6X3fCiKe4Ag5RjwrYD3BMaYu9zvIwYQN8jFKV/UEytlAQs2/GijOfN5fkI3vSNuXhsxcs4UL2PhGvkJpDys0JqgwCE1' 

gateway:
  ip: 172.18.0.5
order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: users' order is empty
